def glasgowcoma():
	print('Eyes - 1 = Does not open eyes | 2 = Opens eyes in response to pain ')
	print('3 = Opens eyes in response to voice | 4 = Opens eyes spontaneously ')
	print('\n')
	prompteyes = eval(input ('Enter value for Eyes. '))
	print('\n')	
	print('Verbal - 1 = Makes no sounds | 2 = Incomprehensible sounds ')
	print('3 = Utters inappropriate words | 4 = Confuse, disoriented ')
	print('5 = Oriented, converses normally ')
	print('\n')
	promptverbal = eval(input ('Enter value for Verbal. '))
	print('\n')
	print('Motor - 1 = Makes no movements | 2 = Extension to painful stimuli (decerebrate) ')
	print('3 = Abnormal Flexion to painful stimuli (decorticate) | 4 = Flexion / Withdrawal to painful stimuli ')
	print('5 = Localizes painful stimuli | 6 = Obeys commands ')
	print('\n')
	promptmotor = eval(input ('Enter value for Motor. '))
	print('\n')
	try:
		totalgcs = int(prompteyes) + int(promptverbal) + int(promptmotor)
		print(('Total GCS score = ' + str(int(totalgcs)) + '. '))
	except:
		print('Please enter valid integers when prompted.\n')
	print('\n')
	return
